# .github/stale.yml

daysUntilStale: 30
daysUntilClose: 7
staleLabel: "stale"
exemptLabels:
  - "pinned"
  - "security"
staleIssueMessage: "This issue has been automatically marked as stale due to inactivity. If this is still a problem, please provide an update. Otherwise, this issue will be closed in 7 days. Thank you!"
closeIssueMessage: "This issue has been automatically closed due to inactivity. If you still need help, please feel free to reopen it. Thank you!"
